storeRoot: /glogcenter
storeChanLength: 64
maxIdleTime: 180
storeNameAutoAddDate: true
serverUrl: ""
serverIp: ""
serverPort: "8080"
contextPath: /glc
enableSecurityKey: false
securityKey: glogcenter
headerSecurityKey: X-GLC-AUTH
tokenSalt: glogcenter
enableAmqpConsume: false
enableWebGzip: false
amqpAddr: ""
amqpQueueName: glc-log-queue
amqpJsonFormat: true
saveDays: 180
enableLogin: true
clusterMode: false
clusterUrls: []
enableBackup: false
glcGroup: default
minioUrl: ""
minioUser: ""
minioPassword: ""
minioBucket: ""
enableUploadMinio: false
goMaxProcess: 16
aryWhite: []
aryBlack: []
testMode: false
mulitLineSearch: false
logLevel: INFO
enableCors: false
pageSize: 100
sessionTimeout: 30
testMod: false
username: admin
password: Admin@@2023
