storeRoot: /glogcenter
storeChanLength: 64
maxIdleTime: 180
storeNameAutoAddDate: true
serverUrl: ""
serverIp: ""
serverPort: "8080"
contextPath: /glc
enableSecurityKey: false
securityKey: glogcenter
headerSecurityKey: X-GLC-AUTH
enableAmqpConsume: false
enableWebGzip: false
amqpAddr: ""
amqpQueueName: glc-log-queue
amqpJsonFormat: true
saveDays: 180
enableLogin: true
user:
- username: admin
  password: admin@@2023
- username: test
  password: admin@@2023
clusterMode: false
clusterUrls: []
enableBackup: false
glcGroup: default
minioUrl: ""
minioUser: ""
minioPassword: ""
minioBucket: ""
enableUploadMinio: false
goMaxProcess: 16
logLevel: INFO
enableCors: false
pageSize: 100
